version: '3.3'

services:
  snippetbox:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'test_snippetbox'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: