# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "preprod" ]
  pull_request:
    branches: [ "preprod" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Set up Database
      run: docker compose -f docker/docker-compose-test.yaml up

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
